const express=require("express")
const { getAllBuys,addBuy,deleteBuy,updateBuy, getBuyById } = require("../controllers/BuyController")
const verifyJWT = require("../middlewares/verifyJWT")
const router=express.Router()
router.get('/',getAllBuys)
router.post('/',addBuy)
router.delete('/:id',verifyJWT,deleteBuy)
router.put('/:id',verifyJWT,updateBuy)
router.get('/:id',verifyJWT,getBuyById)
module.exports=router